# Streamlit Cloud secrets configuration
# This file is used by Streamlit Cloud to store secrets

# No actual secrets are needed for this application
# This file is just a placeholder

[general]
# Add any secrets here if needed in the future
deployment_environment = "cloud"
