# This file contains secrets and configuration for Streamlit Cloud
# You can add your secrets here, but make sure not to commit sensitive information

# Example of a secret (uncomment and modify as needed)
# [api_keys]
# some_api_key = "your-api-key-here"
